In [1]:
import numpy as np

# 打开IN文件
with open('C:/Users/15541/Desktop/2sem/geo/progam2/5.in', 'r') as f:
    # 读取m和n
    m = int(f.readline().strip())
    n = int(f.readline().strip())

    # 读取n个点的名称和坐标
    data = []
    for i in range(n):
        line = f.readline().split()
        name = line[0]
        coords = np.array([float(x) for x in line[1:]])
        data.append((name, coords))

    # 创建n*m的numpy array
    mul = np.zeros((1, n))
    point = np.zeros((1, m))
    n_array = np.empty((n, m))
    for i in range(n):
        n_array[i] = data[i][1]
        
    # 读取p个点的名称和坐标
    p = int(f.readline().strip())

    # 构造affine约束矩阵
    a_n = np.zeros((1, n+p))
    a_n[:, :n] = 1
    a_p = np.zeros((1, n+p))
    a_p [0, -p:] = 1
    a = np.zeros((m+2, 1))
    a[-2:] = 1

    queries = []
    for i in range(p):
        line = f.readline().split()
        name = line[0]
        coords = np.array([float(x) for x in line[1:]])
        queries.append((name, coords))

    # 创建p*m的numpy array
    p_array = np.empty((p, m))
    for i in range(p):
        p_array[i] = queries[i][1]

    # 整合成矩阵
    nep_array= -p_array
    ma = np.concatenate((n_array, -p_array), axis=0)
    ma0 = np.transpose(ma)
    ma1 = np.concatenate((ma0, a_n), axis=0)
    matrix = np.concatenate((ma1, a_p), axis=0)
    all_matrix = np.concatenate((matrix, a), axis=1)


    if np.linalg.matrix_rank(matrix) != np.linalg.matrix_rank(all_matrix):
        print("N")
    else:
            # 求解方程组
        arr = np.zeros(m + 2)
        arr[-2:] = 1
        x, residuals, rank, s = np.linalg.lstsq(matrix, arr,rcond=None)
        for i in range(n):
            mul[0][i] = x[i]
        end = np.dot(mul, n_array)
        output = "Y"
        for i in range(m):
            output += " "
            output += str(end[0][i])
        print(output)

Y -6.357650080969451 1.164401310102641 -6.578557089846113 -7.487978677337052 3.533979240190789 -1.800022062033813 3.948616663443728


In [4]:
matrix

array([[ 6.0634  ,  5.97911 ,  6.08737 ,  5.90099 ,  5.99912 ,  6.00621 ,
         6.0262  ,  6.03283 ,  5.90555 ,  6.03258 ,  5.95454 ,  5.90477 ,
         5.81759 ,  5.94153 ,  5.96868 ,  5.94595 ,  5.99451 ,  5.92829 ,
         5.97506 ,  5.98516 ,  6.10378 ,  6.02686 ,  6.03663 ,  5.86382 ,
         6.05284 ,  5.95273 ,  3.68198 ,  2.76814 ],
       [-4.49499 , -3.96646 , -4.64532 , -3.47663 , -4.09194 , -4.13642 ,
        -4.26175 , -4.30332 , -3.50523 , -4.30174 , -3.81238 , -3.50034 ,
        -2.95366 , -3.7308  , -3.90104 , -3.75852 , -4.06305 , -3.64782 ,
        -3.9411  , -4.0044  , -4.74818 , -4.26586 , -4.32717 , -3.24356 ,
        -4.42879 , -3.80105 , -1.54234 , -1.67142 ],
       [-5.60818 , -6.07289 , -5.47599 , -6.50358 , -5.96256 , -5.92345 ,
        -5.81325 , -5.77671 , -6.47843 , -5.77809 , -6.20836 , -6.48273 ,
        -6.9634  , -6.28009 , -6.13041 , -6.25572 , -5.98796 , -6.35306 ,
        -6.09519 , -6.03953 , -5.38556 , -5.80964 , -5.75573 , -6.70851 ,
      

In [24]:
#求解的方程组 matrix 和 arr
matrix.shape

(9, 28)

In [23]:
arr

array([0., 0., 0., 0., 0., 0., 0., 1., 1.])

In [2]:
n_vector= np.empty((m, n-1))
for i in range(m):
    for j in range(n-1):
        n_vector[i][j] = n_array[j+1][i]-n_array[0][i]

In [3]:
n_vector.shape

(7, 25)

In [4]:
p_vector= np.empty((m, p-1))
for i in range(m):
    for j in range(p-1):
        p_vector[i][j] = p_array[j+1][i]-p_array[0][i]

In [5]:
k_matrix = np.concatenate((n_vector, p_vector), axis=1)

In [6]:
np.linalg.matrix_rank(k_matrix)

7

In [12]:
k_matrix.shape

(7, 26)

In [16]:
n_vector.shape

(7, 25)

In [7]:
arr2=np.zeros(m)
for i in range(m):
    arr2[i]=p_array[0][i]-n_array[0][i]

In [8]:
x, residuals, rank, s = np.linalg.lstsq(k_matrix, arr2,rcond=None)

In [13]:
arr2.shape

(7,)

In [9]:
mul2 = np.zeros((1, n-1))
for i in range(n-1):
    mul2[0][i] = x[i]

In [10]:
out_point = np.zeros(m)
for i in range(m):
    out_point[i] = n_array[0][i]
for i in range(m):
    for j in range(n-1):
        out_point[i]=out_point[i]+mul2[0][j]*n_vector[i][j]

In [11]:
out_point

array([-6.22804715,  1.18270774, -6.37534907, -7.34197825,  3.2890407 ,
       -1.69354099,  3.9354825 ])

In [1]:
import numpy as np

def print_array(array):
    for row in array:
        print(' '.join(map(str, row)))

# 示例用法
M, N = 3, 4
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print_array(array)

1 2 3 4
5 6 7 8
9 10 11 12
